# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Views/UI/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cameraLayout = QtWidgets.QVBoxLayout()
        self.cameraLayout.setObjectName("cameraLayout")
        self.cameraImageLayout = QtWidgets.QVBoxLayout()
        self.cameraImageLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.cameraImageLayout.setObjectName("cameraImageLayout")
        self.cameraImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraImage.sizePolicy().hasHeightForWidth())
        self.cameraImage.setSizePolicy(sizePolicy)
        self.cameraImage.setText("")
        self.cameraImage.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraImage.setObjectName("cameraImage")
        self.cameraImageLayout.addWidget(self.cameraImage)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.cameraImageLayout.addItem(spacerItem)
        self.cameraLayout.addLayout(self.cameraImageLayout)
        self.horizontalLayout.addLayout(self.cameraLayout)
        self.settingsLayout = QtWidgets.QVBoxLayout()
        self.settingsLayout.setObjectName("settingsLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(180, 0))
        self.startButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.startButton.setObjectName("startButton")
        self.settingsLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setMinimumSize(QtCore.QSize(180, 0))
        self.stopButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.stopButton.setObjectName("stopButton")
        self.settingsLayout.addWidget(self.stopButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.settingsLayout.addItem(spacerItem1)
        self.databaseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseButton.sizePolicy().hasHeightForWidth())
        self.databaseButton.setSizePolicy(sizePolicy)
        self.databaseButton.setMinimumSize(QtCore.QSize(180, 0))
        self.databaseButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.databaseButton.setObjectName("databaseButton")
        self.settingsLayout.addWidget(self.databaseButton)
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.settingsButton.setObjectName("settingsButton")
        self.settingsLayout.addWidget(self.settingsButton)
        self.notificationButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notificationButton.sizePolicy().hasHeightForWidth())
        self.notificationButton.setSizePolicy(sizePolicy)
        self.notificationButton.setMinimumSize(QtCore.QSize(180, 0))
        self.notificationButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.notificationButton.setObjectName("notificationButton")
        self.settingsLayout.addWidget(self.notificationButton)
        self.horizontalLayout.addLayout(self.settingsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Security"))
        self.startButton.setText(_translate("MainWindow", "Старт"))
        self.stopButton.setText(_translate("MainWindow", "Стоп"))
        self.databaseButton.setText(_translate("MainWindow", "База данных лиц"))
        self.settingsButton.setText(_translate("MainWindow", "Настройка обработки"))
        self.notificationButton.setText(_translate("MainWindow", "Настройка оповещений"))


